#External configs
notifications:
  email:
    recipients:
      - unborntech@gmail.com
    on_success: change
    on_failure: change

# Build configs
addons:
    postgresql: "9.6"
services:
  - postgresql
#   - redis-server

# Build runs
before_install:
  - sudo . setup.sh
    
install:
  - npm install

# before_script:
    
# script:
    