version: 0.0.1
port: 8080
devmode: true
secret: this_will_be_generated_when_you_install_the_app_installation
site:
  name: Tauchan Imageboard
  desc: An imageboard based on the tauchan imageboard framework.
  keywords:
    - anonymous
    - imageboard
    - tauchan framework
    - nodejs
    - forum
database:
  host: localhost
  port: 5432
  database: tauchan
  user: tauchan
  password: tauchan
options:
  hash_ip_mask: true
  disable_usermade_boards: false
  reserve_single_char_boards: true
  require_valid_email: false
values:
  max_upload_size_in_kb: 8096
  cdn_domain: localhost
  poster_id_length: 10
  max_custom_board_pages: 10
  tag_cloud_count: 25
capcodes:
  - Admin
  - Owner
  - Manager
custom_tripcodes:
  '#demotrip': '4ctual_tr!p'
  '##demosecuretrip': '4ctual_$ecur3_tr!p'
root_whitelist:
  - favicon.ico
external_sources:
  'socket.io.js': 'https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js'
markdown:
  suppress:
    all: '@!'
    paragraph: '@@'
    open: '@>'
    close: '<@'
  list:
    - key: '-'
      ordered: false
    - key: '+'
      ordered: true
      class: 'number'
    - key: '='
      ordered: true
      class: 'bigalpha'
    - key: '*'
      ordered: true
      class: 'smallalpha'
  custom:
    -	key: '__'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: '<u>'
      close: '</u>'
    -	key: '__'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: '<u>'
      close: '</u>'
    -	key: ''
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: '<u>'
      close: '</u>'
    - key: '**'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: false
      open: '<span class="spoiler">'
      close: '</span>'
