version: 0.0.1
port: 3000
site:
  name: Tauchan Imageboard
  secret: this_will_be_generated_when_you_run_the_app_installation
  devmode: true
database:
  host: localhost
  port: 5433
  database: tauchan
  user: postgres
  password: postgres
options:
  hash_ip_mask: true
  disable_usermade_boards: false
  reserve_single_char_boards: true
  require_valid_email: false
values:
  max_upload_size_in_kb: 8096
  cdn_domain: localhost