version: 0.0.3
port: 8080
devmode: true
secret: this_will_be_generated_when_you_run_the_app_installation
site:
  name: Tauchan Imageboard
  desc: An imageboard based on the tauchan imageboard framework.
  keywords:
    - anonymous
    - imageboard
    - tauchan framework
    - nodejs
    - forum
database:
  host: localhost
  port: 5432
  database: tauchan
  user: tauchan
  password: tauchan
options:
  hash_ip_mask: true
  disable_usermade_boards: false
  reserve_single_char_boards: true
  require_valid_email: false
values:
  max_upload_size_in_kb: 8096
  cdn_domain: localhost
  poster_id_length: 10
  max_custom_board_pages: 10
  tag_cloud_count: 25
capcodes:
  - Admin
  - Owner
  - Manager
  - Vol
custom_tripcodes:
  '#demotrip': '4ctual_tr!p'
  '##demosecuretrip': '4ctual_$ecur3_tr!p'
root_whitelist:
  - favicon.ico
external_sources:
  'socket.io.js': 'https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js'
external_whitelist:
  style: 
  script:
    - cdnjs.cloudflare.com
  raw:
    - i.imgur.com
    - imgur.com
    - dummyimage.com
    - i.ytimg.com
    - img.youtube.com
    - '*.dmcdn.net'
  embed:
    - www.youtube.com
    - youtube.com
    - youtu.be
    - www.dailymotion.com
    - dailymotion.com
    - dai.ly
external_media:
  imgur: '^https?:\/\/(?:i\.)?imgur\.com\/[^/.]+\.(?:jpg|png|gif)+'
  dummyimage: '^https?:\/\/dummyimage\.com'
  youtube:
      - '^https?:\/\/(?:www\.)?youtube\.com'
      - '^https?:\/\/youtu\.be'
  dailymotion:
      - '^https?:\/\/(?:www\.)?dailymotion\.com\/video\/[a-zA-Z0-9]+'
      - '^https?:\/\/dai.ly\/[a-zA-Z0-9]+'
markdown:
  hyperlink: '&'
  ignore:
    all: '@!'
    paragraph: '@@'
    string: '@&'
    open: '@>'
    close: '<@'
  list:
    - key: '-'
      ordered: false
    - key: '+'
      ordered: true
      class: 'number'
    - key: '='
      ordered: true
      class: 'bigalpha'
    - key: '*'
      ordered: true
      class: 'smallalpha'
  custom:
    # - key: 'string' # this is the key that the parser looks for (required)
    #   exclusiveline: true # this denotes that the markdown requires to encase a single line of text
    #   exclusivetext: false # this denotes that all markdown inside of this key will be ignored
    #   nolinebreak: false # this denotes that line breaks are not allowed inside this key
    #   brick: true # this wraps the key in braces similar to bbcode style syntax eg. [string][/string]
    #   open: '<span class="special">' # this is the opening markup, can be whatever needed (required)
    #   close: '</span>' # this is the closing markup, can be whatever needed (required)
    - key: '=='
      exclusiveline: true
      open: '<span class="important">'
      close: '</span>'
    - key: '__'
      open: '<u>'
      close: '</u>'
    - key: '""'
      open: '<i>'
      close: '</i>'
    - key: '**'
      open: '<b>'
      close: '</b>'
    - key: '~~'
      open: '<del>'
      close: '</del>'
    - key: 's'
      brick: true
      open: '<span class="spoiler">'
      close: '</span>'
    - key: '```'
      exclusivetext: true
      open: '<pre><code>'
      close: '</code></pre>'
    - key: '``'
      exclusivetext: true
      open: '<code>'
      close: '</code>'
    - key: 'code'
      brick: true
      exclusivetext: true
      open: '<pre><code>'
      close: '</code></pre>'

