version: 0.0.1
port: 8080
devmode: true
secret: this_will_be_generated_when_you_install_the_app_installation
site:
  name: Tauchan Imageboard
  desc: An imageboard based on the tauchan imageboard framework.
  keywords:
    - anonymous
    - imageboard
    - tauchan framework
    - nodejs
    - forum
database:
  host: localhost
  port: 5432
  database: tauchan
  user: tauchan
  password: tauchan
options:
  hash_ip_mask: true
  disable_usermade_boards: false
  reserve_single_char_boards: true
  require_valid_email: false
values:
  max_upload_size_in_kb: 8096
  cdn_domain: localhost
  poster_id_length: 10
  max_custom_board_pages: 10
  tag_cloud_count: 25
capcodes:
  - Admin
  - Owner
  - Manager
custom_tripcodes:
  '#demotrip': '4ctual_tr!p'
  '##demosecuretrip': '4ctual_$ecur3_tr!p'
external_sources:
  'socket.io.js': 'https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.4.8/socket.io.min.js'
root_whitelist:
  - favicon.ico
external_media:
  imgur:
    type: raw
    regex: '^https?:\/\/(?:i\.)?imgur\.com\/[^/.]+\.(?:jpg|png|gif)+'
    domains:
      - i.imgur.com
      - imgur.com
  dummyimage:
    type: raw
    regex: '^https?:\/\/dummyimage\.com'
    domains:
      - dummyimage.com
  youtube:
    type: embed
    regex:
      - '^https?:\/\/(?:www\.)?youtube\.com'
      - '^https?:\/\/youtu\.be'
    domains:
      - www.youtube.com
      - youtube.com
      - youtu.be
  dailymotion:
    type: embed
    regex:
      - '^https?:\/\/(?:www\.)?dailymotion\.com\/video\/[a-zA-Z0-9]+'
      - '^https?:\/\/dai.ly\/[a-zA-Z0-9]+'
    domains:
      - www.dailymotion.com
      - dailymotion.com
      - dai.ly
markdown:
  hyperlink: '&'
  ignore:
    all: '@!'
    paragraph: '@@'
    string: '@&'
    open: '@>'
    close: '<@'
  list:
    - key: '-'
      ordered: false
    - key: '+'
      ordered: true
      class: 'number'
    - key: '='
      ordered: true
      class: 'bigalpha'
    - key: '*'
      ordered: true
      class: 'smallalpha'
  custom:
    - key: '=='
      brick: false
      exclusivetext: false
      exclusiveline: true
      multiline: false
      open: <span class="important">
      close: </span>
    - key: '__'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: <u>
      close: </u>
    - key: "\"\""
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: <i>
      close: </i>
    - key: '**'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: <b>
      close: </b>
    - key: '~~'
      brick: false
      exclusivetext: false
      exclusiveline: false
      multiline: true
      open: <span class="spoiler">
      close: </span>

