CREATE USER tauchan SUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;
CREATE DATABASE tauchan WITH OWNER tauchan;
\connect tauchan
CREATE TYPE LOGLEVEL AS ENUM ('info','notice','warning','error','server');
CREATE EXTENSION IF NOT EXISTS pgcrypto;