ALTER TABLE boards ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE threads ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE pages ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE users ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE bans ADD COLUMN modified TIMESTAMP NOT NULL DEFAULT NOW();
